In [4]:
import pandas as pd
import numpy as np 
import matplotlib as plt 

pd.set_option('display.max_colwidth', None)

tweets = pd.read_csv('no_punctuation2.csv', encoding='utf-8')
tweets.head(15)

sentiment  \
0    NEUTRAL   
1    NEUTRAL   
2    NEUTRAL   
3   NEGATIVE   
4    NEUTRAL   
5    NEUTRAL   
6    NEUTRAL   
7    NEUTRAL   
8    NEUTRAL   
9    NEUTRAL   
10  POSITIVE   
11  POSITIVE   
12  POSITIVE   
13   NEUTRAL   
14   NEUTRAL   

                                                                                                                                                                                                                                              text_without_punctuation  
0   Bayer Leverkusen goalkeeper Bernd Leno will not be going to Napoli His agent Uli Ferber to Bild I can confirm that there were negotiations with Napoli which we have broken off Napoli is not an option Atletico Madrid and Arsenal are the other strong rumours    
1                                                                                                                                                                                                              Gary Speed v Blackburn at St James in 200102 anyone      
2                                                                                                                                                                                                                    Dont make him regret it and start him over Hoofiz  
3                                                                                                                                                                                          Hes a liar made up Ive unfollowed him as loads of others have Pure blagger   
4                                                                                                                                          Didnt realise Kenwright is due to leave at the end of the month In all seriousness could you see him being interested in us  
5                                                                                                                                                                                                          My knowledge has decreased somewhat in the past few seasons  
6                                                                                                                                                                                               Report Linked with  and  Italians set to sign £45mrated winger  HITC   
7                                                                                                           Am seeing tweets that there’s been a fall out  between the money men I’m presuming it’s just a quiet news day or some kopite with nothing better to do   
8                                                                                                                                                                                                                        Expect loads of excuses after tonight’s game  
9                                                                                                                                                                                   I’m just fine I have your fanbase angry over stating facts should ask them hun Xo  
10                                                                                                                                                                                                                   What a weekend of football results    amp Hearts   
11                                                                                                                                              For the first time in a long while my heart was relaxed while watching Chelsea Really enjoyed it today Come on CHELSEA  
12                                                                                                                                                                                                                  What a fantastic signing worth every single penny   
13                                  

In [5]:
tweets = tweets.dropna()
print(tweets.isnull().sum())

sentiment                   0
text_without_punctuation    0
dtype: int64


In [7]:
# Find the indices of rows with Mixed sentiment
mixed_indices = tweets[tweets['sentiment'] == 'MIXED'].index

# Delete the rows with Mixed sentiment
tweets = tweets.drop(mixed_indices)

# Print the resulting DataFrame
print(tweets.head())

  sentiment  \
0   NEUTRAL   
1   NEUTRAL   
2   NEUTRAL   
3  NEGATIVE   
4   NEUTRAL   

                                                                                                                                                                                                                                             text_without_punctuation  
0  Bayer Leverkusen goalkeeper Bernd Leno will not be going to Napoli His agent Uli Ferber to Bild I can confirm that there were negotiations with Napoli which we have broken off Napoli is not an option Atletico Madrid and Arsenal are the other strong rumours    
1                                                                                                                                                                                                             Gary Speed v Blackburn at St James in 200102 anyone      
2                                                                                                                    

In [8]:
positive_tweets = tweets[tweets['sentiment'] == 'POSITIVE']
negative_tweets = tweets[tweets['sentiment'] == 'NEGATIVE']
neutral_tweets = tweets[tweets['sentiment'] == 'NEUTRAL']
mixed_tweets = tweets[tweets['sentiment'] == 'MIXED']

print('No of positive tagged tweets is: {}'.format(len(positive_tweets)))
print('No of negative tagged tweets is: {}'.format(len(negative_tweets)))
print('No of neutral tagged tweets is: {}'.format(len(neutral_tweets)))
print('No of mixed tagged tweets is: {}'.format(len(mixed_tweets)))

No of positive tagged tweets is: 1070334
No of negative tagged tweets is: 354501
No of neutral tagged tweets is: 3549912
No of mixed tagged tweets is: 0


In [10]:
import pandas as pd

# Shuffle the DataFrame to ensure that the downsampling is random
tweets = tweets.sample(frac=1, random_state=42)

# Count the number of tweets in each sentiment class
counts = tweets['sentiment'].value_counts()

# Find the smallest class size
smallest_size = counts.min()

# Downsample each class to the smallest size
positive_tweets = tweets[tweets['sentiment'] == 'POSITIVE'].sample(n=smallest_size, random_state=42)
negative_tweets = tweets[tweets['sentiment'] == 'NEGATIVE'].sample(n=smallest_size, random_state=42)
neutral_tweets = tweets[tweets['sentiment'] == 'NEUTRAL'].sample(n=smallest_size, random_state=42)

# Concatenate the downsampled DataFrames
tweets = pd.concat([positive_tweets, negative_tweets, neutral_tweets], ignore_index=True)

# Print the new counts of tweets in each class
print('No of positive tagged tweets is: {}'.format(len(tweets[tweets['sentiment'] == 'POSITIVE'])))
print('No of negative tagged tweets is: {}'.format(len(tweets[tweets['sentiment'] == 'NEGATIVE'])))
print('No of neutral tagged tweets is: {}'.format(len(tweets[tweets['sentiment'] == 'NEUTRAL'])))

No of positive tagged tweets is: 354501
No of negative tagged tweets is: 354501
No of neutral tagged tweets is: 354501


In [11]:
import warnings
warnings.filterwarnings('ignore')
import re
import string
import pickle

urlPattern = r"((http://)[^ ]*|(https://)[^ ]*|( www\.)[^ ]*)"
userPattern = '@[^\s]+'
some = 'amp,today,tomorrow,going,girl'

def process_tweets(tweet):
  # Lower Casing
    tweet = re.sub(r"he's", "he is", tweet)
    tweet = re.sub(r"there's", "there is", tweet)
    tweet = re.sub(r"We're", "We are", tweet)
    tweet = re.sub(r"That's", "That is", tweet)
    tweet = re.sub(r"won't", "will not", tweet)
    tweet = re.sub(r"they're", "they are", tweet)
    tweet = re.sub(r"Can't", "Cannot", tweet)
    tweet = re.sub(r"wasn't", "was not", tweet)
    tweet = re.sub(r"don\x89Ûªt", "do not", tweet)
    tweet = re.sub(r"aren't", "are not", tweet)
    tweet = re.sub(r"isn't", "is not", tweet)
    tweet = re.sub(r"What's", "What is", tweet)
    tweet = re.sub(r"haven't", "have not", tweet)
    tweet = re.sub(r"hasn't", "has not", tweet)
    tweet = re.sub(r"There's", "There is", tweet)
    tweet = re.sub(r"He's", "He is", tweet)
    tweet = re.sub(r"It's", "It is", tweet)
    tweet = re.sub(r"You're", "You are", tweet)
    tweet = re.sub(r"I'M", "I am", tweet)
    tweet = re.sub(r"shouldn't", "should not", tweet)
    tweet = re.sub(r"wouldn't", "would not", tweet)
    tweet = re.sub(r"i'm", "I am", tweet)
    tweet = re.sub(r"I\x89Ûªm", "I am", tweet)
    tweet = re.sub(r"I'm", "I am", tweet)
    tweet = re.sub(r"Isn't", "is not", tweet)
    tweet = re.sub(r"Here's", "Here is", tweet)
    tweet = re.sub(r"you've", "you have", tweet)
    tweet = re.sub(r"you\x89Ûªve", "you have", tweet)
    tweet = re.sub(r"we're", "we are", tweet)
    tweet = re.sub(r"what's", "what is", tweet)
    tweet = re.sub(r"couldn't", "could not", tweet)
    tweet = re.sub(r"we've", "we have", tweet)
    tweet = re.sub(r"it\x89Ûªs", "it is", tweet)
    tweet = re.sub(r"doesn\x89Ûªt", "does not", tweet)
    tweet = re.sub(r"It\x89Ûªs", "It is", tweet)
    tweet = re.sub(r"Here\x89Ûªs", "Here is", tweet)
    tweet = re.sub(r"who's", "who is", tweet)
    tweet = re.sub(r"I\x89Ûªve", "I have", tweet)
    tweet = re.sub(r"y'all", "you all", tweet)
    tweet = re.sub(r"can\x89Ûªt", "cannot", tweet)
    tweet = re.sub(r"would've", "would have", tweet)
    tweet = re.sub(r"it'll", "it will", tweet)
    tweet = re.sub(r"we'll", "we will", tweet)
    tweet = re.sub(r"wouldn\x89Ûªt", "would not", tweet)
    tweet = re.sub(r"We've", "We have", tweet)
    tweet = re.sub(r"he'll", "he will", tweet)
    tweet = re.sub(r"Y'all", "You all", tweet)
    tweet = re.sub(r"Weren't", "Were not", tweet)
    tweet = re.sub(r"Didn't", "Did not", tweet)
    tweet = re.sub(r"they'll", "they will", tweet)
    tweet = re.sub(r"they'd", "they would", tweet)
    tweet = re.sub(r"DON'T", "DO NOT", tweet)
    tweet = re.sub(r"That\x89Ûªs", "That is", tweet)
    tweet = re.sub(r"they've", "they have", tweet)
    tweet = re.sub(r"i'd", "I would", tweet)
    tweet = re.sub(r"should've", "should have", tweet)
    tweet = re.sub(r"You\x89Ûªre", "You are", tweet)
    tweet = re.sub(r"where's", "where is", tweet)
    tweet = re.sub(r"Don\x89Ûªt", "Do not", tweet)
    tweet = re.sub(r"we'd", "we would", tweet)
    tweet = re.sub(r"i'll", "I will", tweet)
    tweet = re.sub(r"weren't", "were not", tweet)
    tweet = re.sub(r"They're", "They are", tweet)
    tweet = re.sub(r"Can\x89Ûªt", "Cannot", tweet)
    tweet = re.sub(r"you\x89Ûªll", "you will", tweet)
    tweet = re.sub(r"I\x89Ûªd", "I would", tweet)
    tweet = re.sub(r"let's", "let us", tweet)
    tweet = re.sub(r"it's", "it is", tweet)
    tweet = re.sub(r"can't", "cannot", tweet)
    tweet = re.sub(r"don't", "do not", tweet)
    tweet = re.sub(r"you're", "you are", tweet)
    tweet = re.sub(r"i've", "I have", tweet)
    tweet = re.sub(r"that's", "that is", tweet)
    tweet = re.sub(r"i'll", "I will", tweet)
    tweet = re.sub(r"doesn't", "does not", tweet)
    tweet = re.sub(r"i'd", "I would", tweet)
    tweet = re.sub(r"didn't", "did not", tweet)
    tweet = re.sub(r"ain't", "am not", tweet)
    tweet = re.sub(r"you'll", "you will", tweet)
    tweet = re.sub(r"I've", "I have", tweet)
    tweet = re.sub(r"Don't", "do not", tweet)
    tweet = re.sub(r"I'll", "I will", tweet)
    tweet = re.sub(r"I'd", "I would", tweet)
    tweet = re.sub(r"Let's", "Let us", tweet)
    tweet = re.sub(r"you'd", "You would", tweet)
    tweet = re.sub(r"It's", "It is", tweet)
    tweet = re.sub(r"Ain't", "am not", tweet)
    tweet = re.sub(r"Haven't", "Have not", tweet)
    tweet = re.sub(r"Could've", "Could have", tweet)
    tweet = re.sub(r"youve", "you have", tweet)  
    tweet = re.sub(r"donå«t", "do not", tweet)  
    
    tweet = re.sub(r"some1", "someone", tweet)
    tweet = re.sub(r"yrs", "years", tweet)
    tweet = re.sub(r"hrs", "hours", tweet)
    tweet = re.sub(r"2morow|2moro", "tomorrow", tweet)
    tweet = re.sub(r"2day", "today", tweet)
    tweet = re.sub(r"4got|4gotten", "forget", tweet)
    tweet = re.sub(r"b-day|bday", "b-day", tweet)
    tweet = re.sub(r"mother's", "mother", tweet)
    tweet = re.sub(r"mom's", "mom", tweet)
    tweet = re.sub(r"dad's", "dad", tweet)
    tweet = re.sub(r"hahah|hahaha|hahahaha", "haha", tweet)
    tweet = re.sub(r"lmao|lolz|rofl", "lol", tweet)
    tweet = re.sub(r"thanx|thnx", "thanks", tweet)
    tweet = re.sub(r"goood", "good", tweet)
    tweet = re.sub(r"some1", "someone", tweet)
    tweet = re.sub(r"some1", "someone", tweet)
    tweet = tweet.lower()
    tweet=tweet[1:]

    import WordNetLemmatizer

        #reducing a word to its word stem 
    wordLemm = WordNetLemmatizer()
    finalwords=[]
    for w in final_tokens:
      if len(w)>1:
        word = wordLemm.lemmatize(w)
        finalwords.append(word)
    return ' '.join(finalwords)

In [12]:
abbreviations = {
    "$" : " dollar ",
    "€" : " euro ",
    "4ao" : "for adults only",
    "a.m" : "before midday",
    "a3" : "anytime anywhere anyplace",
    "aamof" : "as a matter of fact",
    "acct" : "account",
    "adih" : "another day in hell",
    "afaic" : "as far as i am concerned",
    "afaict" : "as far as i can tell",
    "afaik" : "as far as i know",
    "afair" : "as far as i remember",
    "afk" : "away from keyboard",
    "app" : "application",
    "approx" : "approximately",
    "apps" : "applications",
    "asap" : "as soon as possible",
    "asl" : "age, sex, location",
    "atk" : "at the keyboard",
    "ave." : "avenue",
    "aymm" : "are you my mother",
    "ayor" : "at your own risk", 
    "b&b" : "bed and breakfast",
    "b+b" : "bed and breakfast",
    "b.c" : "before christ",
    "b2b" : "business to business",
    "b2c" : "business to customer",
    "b4" : "before",
    "b4n" : "bye for now",
    "b@u" : "back at you",
    "bae" : "before anyone else",
    "bak" : "back at keyboard",
    "bbbg" : "bye bye be good",
    "bbc" : "british broadcasting corporation",
    "bbias" : "be back in a second",
    "bbl" : "be back later",
    "bbs" : "be back soon",
    "be4" : "before",
    "bfn" : "bye for now",
    "blvd" : "boulevard",
    "bout" : "about",
    "brb" : "be right back",
    "bros" : "brothers",
    "brt" : "be right there",
    "bsaaw" : "big smile and a wink",
    "btw" : "by the way",
    "bwl" : "bursting with laughter",
    "c/o" : "care of",
    "cet" : "central european time",
    "cf" : "compare",
    "cia" : "central intelligence agency",
    "csl" : "can not stop laughing",
    "cu" : "see you",
    "cul8r" : "see you later",
    "cv" : "curriculum vitae",
    "cwot" : "complete waste of time",
    "cya" : "see you",
    "cyt" : "see you tomorrow",
    "dae" : "does anyone else",
    "dbmib" : "do not bother me i am busy",
    "diy" : "do it yourself",
    "dm" : "direct message",
    "dwh" : "during work hours",
    "e123" : "easy as one two three",
    "eet" : "eastern european time",
    "eg" : "example",
    "embm" : "early morning business meeting",
    "encl" : "enclosed",
    "encl." : "enclosed",
    "etc" : "and so on",
    "faq" : "frequently asked questions",
    "fawc" : "for anyone who cares",
    "fb" : "facebook",
    "fc" : "fingers crossed",
    "fig" : "figure",
    "fimh" : "forever in my heart", 
    "ft." : "feet",
    "ft" : "featuring",
    "ftl" : "for the loss",
    "ftw" : "for the win",
    "fwiw" : "for what it is worth",
    "fyi" : "for your information",
    "g9" : "genius",
    "gahoy" : "get a hold of yourself",
    "gal" : "get a life",
    "gcse" : "general certificate of secondary education",
    "gfn" : "gone for now",
    "gg" : "good game",
    "gl" : "good luck",
    "glhf" : "good luck have fun",
    "gmt" : "greenwich mean time",
    "gmta" : "great minds think alike",
    "gn" : "good night",
    "g.o.a.t" : "greatest of all time",
    "goat" : "greatest of all time",
    "goi" : "get over it",
    "gps" : "global positioning system",
    "gr8" : "great",
    "gratz" : "congratulations",
    "gyal" : "girl",
    "h&c" : "hot and cold",
    "hp" : "horsepower",
    "hr" : "hour",
    "hrh" : "his royal highness",
    "ht" : "height",
    "ibrb" : "i will be right back",
    "ic" : "i see",
    "icq" : "i seek you",
    "icymi" : "in case you missed it",
    "idc" : "i do not care",
    "idgadf" : "i do not give a damn fuck",
    "idgaf" : "i do not give a fuck",
    "idk" : "i do not know",
    "ie" : "that is",
    "i.e" : "that is",
    "ifyp" : "i feel your pain",
    "IG" : "instagram",
    "iirc" : "if i remember correctly",
    "ilu" : "i love you",
    "ily" : "i love you",
    "imho" : "in my humble opinion",
    "imo" : "in my opinion",
    "imu" : "i miss you",
    "iow" : "in other words",
    "irl" : "in real life",
    "j4f" : "just for fun",
    "jic" : "just in case",
    "jk" : "just kidding",
    "jsyk" : "just so you know",
    "l8r" : "later",
    "lb" : "pound",
    "lbs" : "pounds",
    "ldr" : "long distance relationship",
    "lmao" : "laugh my ass off",
    "lmfao" : "laugh my fucking ass off",
    "lol" : "laughing out loud",
    "ltd" : "limited",
    "ltns" : "long time no see",
    "m8" : "mate",
    "mf" : "motherfucker",
    "mfs" : "motherfuckers",
    "mfw" : "my face when",
    "mofo" : "motherfucker",
    "mph" : "miles per hour",
    "mr" : "mister",
    "mrw" : "my reaction when",
    "ms" : "miss",
    "mte" : "my thoughts exactly",
    "nagi" : "not a good idea",
    "nbc" : "national broadcasting company",
    "nbd" : "not big deal",
    "nfs" : "not for sale",
    "ngl" : "not going to lie",
    "nhs" : "national health service",
    "nrn" : "no reply necessary",
    "nsfl" : "not safe for life",
    "nsfw" : "not safe for work",
    "nth" : "nice to have",
    "nvr" : "never",
    "nyc" : "new york city",
    "oc" : "original content",
    "og" : "original",
    "ohp" : "overhead projector",
    "oic" : "oh i see",
    "omdb" : "over my dead body",
    "omg" : "oh my god",
    "omw" : "on my way",
    "p.a" : "per annum",
    "p.m" : "after midday",
    "pm" : "prime minister",
    "poc" : "people of color",
    "pov" : "point of view",
    "pp" : "pages",
    "ppl" : "people",
    "prw" : "parents are watching",
    "ps" : "postscript",
    "pt" : "point",
    "ptb" : "please text back",
    "pto" : "please turn over",
    "qpsa" : "what happens", 
    "ratchet" : "rude",
    "rbtl" : "read between the lines",
    "rlrt" : "real life retweet", 
    "rofl" : "rolling on the floor laughing",
    "roflol" : "rolling on the floor laughing out loud",
    "rotflmao" : "rolling on the floor laughing my ass off",
    "rt" : "retweet",
    "ruok" : "are you ok",
    "sfw" : "safe for work",
     "sk8" : "skate",
    "smh" : "shake my head",
    "sq" : "square",
    "srsly" : "seriously", 
    "ssdd" : "same stuff different day",
    "tbh" : "to be honest",
    "tbs" : "tablespooful",
    "tbsp" : "tablespooful",
    "tfw" : "that feeling when",
    "thks" : "thank you",
    "tho" : "though",
    "thx" : "thank you",
    "tia" : "thanks in advance",
    "til" : "today i learned",
    "tl;dr" : "too long i did not read",
    "tldr" : "too long i did not read",
    "tmb" : "tweet me back",
    "tntl" : "trying not to laugh",
    "ttyl" : "talk to you later",
    "u" : "you",
    "u2" : "you too",
    "u4e" : "yours for ever",
    "utc" : "coordinated universal time",
    "w/" : "with",
    "w/o" : "without",
    "w8" : "wait",
    "wassup" : "what is up",
    "wb" : "welcome back",
    "wtf" : "what the fuck",
    "wtg" : "way to go",
    "wtpa" : "where the party at",
    "wuf" : "where are you from",
    "wuzup" : "what is up",
    "wywh" : "wish you were here",
    "yd" : "yard",
    "ygtr" : "you got that right",
    "ynk" : "you never know",
    "zzz" : "sleeping bored and tired"
}

In [13]:
def convert_abbrev_in_text(tweets):
    t = []
    words = tweets.split() 
    t = [abbreviations[w.lower()] if w.lower() in abbreviations.keys() else w for w in words]

In [17]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix
import dill

# Create the TF-IDF vectorizers
unigram_bigram_tfidf = TfidfVectorizer(ngram_range=(1, 2))
bigram_stopwords_tfidf = TfidfVectorizer(ngram_range=(2, 2), stop_words='english')
bigram_trigram_tfidf = TfidfVectorizer(ngram_range=(2, 3), stop_words='english')

# Create feature sets for each vectorizer
X_unigram_bigram = unigram_bigram_tfidf.fit_transform(tweets['text_without_punctuation'])
X_bigram_stopwords = bigram_stopwords_tfidf.fit_transform(tweets['text_without_punctuation'])
X_bigram_trigram = bigram_trigram_tfidf.fit_transform(tweets['text_without_punctuation'])

# Create target variable
y = tweets['sentiment']

# Train the Naive Bayes classifiers and evaluate their performance using 5-fold cross-validation
nb_unigram_bigram = MultinomialNB()
scores_unigram_bigram = cross_val_score(nb_unigram_bigram, X_unigram_bigram, y, cv=5)

nb_bigram_stopwords = MultinomialNB()
scores_bigram_stopwords = cross_val_score(nb_bigram_stopwords, X_bigram_stopwords, y, cv=5)

nb_bigram_trigram = MultinomialNB()
scores_bigram_trigram = cross_val_score(nb_bigram_trigram, X_bigram_trigram, y, cv=5)

# Determine the most accurate model and save it using dill
if scores_unigram_bigram.mean() > scores_bigram_stopwords.mean() and scores_unigram_bigram.mean() > scores_bigram_trigram.mean():
    most_accurate_model = nb_unigram_bigram.fit(X_unigram_bigram, y)
    with open('unigram_bigram_model2.dill', 'wb') as f:
        dill.dump(most_accurate_model, f)
elif scores_bigram_stopwords.mean() > scores_unigram_bigram.mean() and scores_bigram_stopwords.mean() > scores_bigram_trigram.mean():
    most_accurate_model = nb_bigram_stopwords.fit(X_bigram_stopwords, y)
    with open('bigram_stopwords_model.dill', 'wb') as f:
        dill.dump(most_accurate_model, f)
else:
    most_accurate_model = nb_bigram_trigram.fit(X_bigram_trigram, y)
    with open('bigram_trigram_model.dill', 'wb') as f:
        dill.dump(most_accurate_model, f)

# Print the accuracy of each fold and confusion matrix for each classifier
print('Accuracy for unigrams with bi-gram features:', scores_unigram_bigram)
print('Average accuracy for unigrams with bi-gram features:', scores_unigram_bigram.mean())
print('Confusion Matrix for unigrams with bi-gram features:', confusion_matrix(y, nb_unigram_bigram.fit(X_unigram_bigram, y).predict(X_unigram_bigram)))

print('Accuracy for bi-grams with stopwords:', scores_bigram_stopwords)
print('Average accuracy for bi-grams with stopwords:', scores_bigram_stopwords.mean())
print('Confusion Matrix for bi-grams with stopwords:', confusion_matrix(y, nb_bigram_stopwords.fit(X_bigram_stopwords, y).predict(X_bigram_stopwords)))

print('Accuracy for bi-grams & tri-grams:', scores_bigram_trigram)
print('Average accuracy for bi-grams & tri-grams:', scores_bigram_trigram.mean())
print('Confusion Matrix for bi-grams & tri-grams:', confusion_matrix(y, nb_bigram_trigram.fit(X_bigram_trigram, y).predict(X_bigram_trigram)))

Accuracy for unigrams with bi-gram features: [0.73513524 0.7363247  0.73496599 0.73404325 0.73657264]
Average accuracy for unigrams with bi-gram features: 0.7354083625520246
Confusion Matrix for unigrams with bi-gram features: [[341350   4155   8996]
 [ 87808 212493  54200]
 [ 30637   9203 314661]]
Accuracy for bi-grams with stopwords: [0.68280356 0.69231927 0.68515428 0.68361072 0.68415139]
Average accuracy for bi-grams with stopwords: 0.6856078417704724
Confusion Matrix for bi-grams with stopwords: [[340988   3747   9766]
 [ 36367 288885  29249]
 [ 13505   5405 335591]]
Accuracy for bi-grams & tri-grams: [0.68035411 0.68827603 0.68145425 0.6796709  0.68053126]
Average accuracy for bi-grams & tri-grams: 0.6820573106869856
Confusion Matrix for bi-grams & tri-grams: [[348570   1463   4468]
 [ 19303 320170  15028]
 [  6870   2277 345354]]
